version: "3.9"
services:
  db:
    container_name: db
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: secret
      - POSTGRES_DB: godiary
    ports:
      - 54320:5432
    expose:
      - 5432
  server:
    container_name: diaryServer
    build: .
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_NAME=godiary
      - DB_HOST=db
      - DB_PORT=5432
    